 apiVersion: v1
 kind: Service
 metadata:
   labels:
     app: menu-item
   name: menu-item-svc
 spec:
   type: ClusterIP
   selector:
     app: menu-item
   ports:
   - name: menu-item-http
     port: 9000
     targetPort: http
