apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: menu-item-ingress
spec:
  rules:
    - host: local-minikube.com
      http:
        paths:
          - path: /
            backend:
              serviceName: menu-item-svc
              servicePort: 9000
