 apiVersion: v1
 kind: Service
 metadata:
   labels:
     app: order
   name: order-svc
 spec:
   type: ClusterIP
   selector:
     app: order
   ports:
   - name: order-http
     port: 9000
     targetPort: http
